---
  - block:
    - name: Install/update system packages required by Django framework & web application that uses it
      package: name="{{ item }}" state=latest
      with_items:
        - build-essential
        - libjpeg-dev
        - python{{ params.virtualenv_python_version }}-dev
        - postgresql-server-dev-all
        - python-psycopg2
        - python-virtualenv
      become: yes

    - name: Prepare virtualenv
      pip:
        requirements: "~/{{ params.django_project_root }}/requirements.txt"
        virtualenv: "~/{{ params.django_project_root }}/.venv"
        virtualenv_python: python{{ params.virtualenv_python_version }}

    - name: Create log files dir
      file: path="~/{{ params.django_project_root }}/logs" state=directory

    - name: Create local_settings file
      template:
        src: "{{ params.django_local_settings_template }}"
        dest: "~/{{ params.django_project_root }}/djangoapp/local_settings.py"

    - name: Run manage.py migrate
      django_manage:
        app_path: "~/{{ params.django_project_root }}"
        command: migrate
        #pythonpath: "{{ application_pythonpath }}"
        virtualenv: "~/{{ params.django_project_root }}/.venv"

    - name: Create uwsgi ini file
      template:
        src: templates/uwsgi.ini.j2
        dest: "~/{{ params.django_project_root }}/uwsgi.ini"

    - name: Start uwsgi
      shell: "~/{{ params.django_project_root }}/.venv/bin/uwsgi --ini ~/{{ params.django_project_root }}/uwsgi.ini"
    when: action == "deploy"
