---
  - block:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install some useful stuff
      package: name={{ item }}
      become: yes
      with_items:
        - build-essential
        - libffi-dev
        - acl
        - mc
        - htop
    when: action == "deploy"

  - block:

    - name: Create {{ params.swapfile_size }} swapfile
      shell: "fallocate -l {{ params.swapfile_size }} /swapfile"
      args:
        creates: /swapfile
      register: create_swapfile
      become: yes

    - name: Enforce swapfile permissions
      file: path=/swapfile state=file owner=root group=root mode=0600
      become: yes
      when: create_swapfile.changed

    - name: set up as as swap
      shell: mkswap /swapfile
      become: yes
      when: create_swapfile.changed

    - name: enable swap
      shell: swapon /swapfile
      become: yes
      when: create_swapfile.changed

    - name: add swapfile to /etc/fstab
      mount:
        name: none
        src: /swapfile
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present
      become: yes
      when: create_swapfile.changed

    - name: configure vm.swappiness
      sysctl:
        name: vm.swappiness
        value: 3
        reload: true
        state: present
      become: yes
      when: create_swapfile.changed
    when: params.swapfile_size > 0
